name: Update MITRE ATT&CK Data

on:
  schedule:
    - cron: "0 0 * * 1" # Exécute chaque lundi à minuit UTC
  workflow_dispatch: # Permet de lancer manuellement

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Cloner le repository
        uses: actions/checkout@v3

      - name: 🛠 Installer les dépendances
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install pandas requests openpyxl stix2

      - name: 🔄 Télécharger et convertir MITRE ATT&CK JSON en Excel
        run: python update_attack_data.py

      - name: 🚀 Commiter et pousser les fichiers Excel mis à jour
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.xlsx
          git commit -m "Mise à jour des fichiers MITRE ATT&CK Excel 📊" || echo "Pas de modifications à commit"
          git push origin master
